### ISSUE TITLE
Bug with join and leave messages of CMI

### ISSUE THREAD

**Issue by NoltoxGit** [Syrent/VelocityVanish#208]
### Server backend version

git-Purpur-2017 (MC: 1.20.1)

### Server backend Java version

Temurin-19.0.2+7

### Server Velocity version

Velocity 3.2.0 build 260

### Server Velocity Java version

Temurin-19.0.2+7

### VelocityVanish version

3.20.0 (custom build give in your discord)

### Describe the bug

There are 2 bugs :
- When I connect to the server (whether with or without the "`velocityvanish.action.vanish.onjoin`" permission), there are [2 messages](https://prnt.sc/j3E7wleprLwI) in the public chat.
- And when I use the `/vanish` command to enable my vanish, it displays both the login and logout [messages](https://prnt.sc/rTkuxl5Mhlml).

### Expected behavior

- For the first bug, it is expected that there will be no messages in the public chat.
- For the second bug, it is expected that there will only show the disconnection message in the public chat.

### Steps to reproduce

Step 1: Have CMI
Step 2: Testing the bugs I've explained

### LuckPerms webview link

https://media.discordapp.net/attachments/1036292004650418216/1132358261962715198/image.png

### VelocityVanish's configuration file
```yml
# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
config_version: 6
default_language: en_US
show_dependency_suggestions: false

# IMPORTANT: Legacy code support is strongly discouraged. It adversely affects performance and lacks new Minecraft chat features.
support_legacy_color_codes: true

# If you're the first player to join the server, Vanish data may not synchronize correctly,
# and you may not enter vanish mode. With this option enabled, you can still enter vanish mode
# if you have operator privileges or the "velocityvanish.action.vanish.force" permission.
# If you weren't previously in vanish mode, you'll be unvanished after a few seconds.
force_vanish_if_first: false

bstats: false

# Leave sounds blank to disable them
# Example: command: ""
sounds:
  command: ENTITY_EXPERIENCE_ORB_PICKUP
  vanish: ENTITY_EXPERIENCE_ORB_PICKUP
  unvanish: ENTITY_EXPERIENCE_ORB_PICKUP

vanish:
  # Show players an actionbar when they are vanished
  actionbar: true
  
  # Remember vanish data after switching servers?
  # Note: Requires Velocity as a proxy server
  remember: true
  
  # Should we change player type to spectator in tablist for players who have permission to see vanished players?
  # Note: Requires ProtocolLib in versions lower than 1.19
  see_as_spectator: false
  
  # Should vanished players be protected from all damage sources?
  invincible: true
  
  # Prevent vanished players from picking up items
  prevent_pickup: true
  
  # You can also achieve this by setting the fake join/leave message to blank in the language file
  fake_join_leave_message: true
  
  silent_open_container: true
  
  prevent:
    block_break: false
    block_place: false
    interact: false

hooks:
  essentials:
    force_prevent_private_messages: false
```
### Plugins

ajLeaderboards, Arceon, AzLink, BanItem, Builders-Utilities, ChatGames, Chunky, Citizens, CMI, *CMIEInjector, CMILib, CoreProtect, craftableinvframes, craftFlowers, DeluxeMenus, DiscordSRV, EternalTags, F3NPerm, FastAsyncVoxelSniper, FastAsyncWorldEdit, FreedomChat, goBrush, goPaint, GSit, HeadBlocks, HeadDatabase, InteractiveChat, ItemEdit, LibsDisguises, LiteBans, LuckPerms, MasterCooldowns, Multiverse-Core, MysteryBoxes, OpenInv, Pl-Hide-Pro, PlaceholderAPI, PlayerPoints, PlotSquared, ProCosmetics, ProtocolLib, spark, TAB, UltimateRewards, Vault, VelocityVanish, ViaBackwards, ViaVersion, VoteParty, WorldEditSelectionVisualizer, WorldGuard

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
