### ISSUE TITLE
Console spam on 1.8

### ISSUE THREAD

**Issue by GronyRalph** [Syrent/VelocityVanish#246]
### Server backend version

1.8.8

### Server backend Java version

17

### Server Velocity version

3.2.0-SNAPSHOT (git-19abb909-b265)

### Server Velocity Java version

17

### VelocityVanish version

3.26.0-build.18

### Describe the bug

The moment I join the console begins spamming this, like every tick, it's so bad that the website where I have my console starts lagging, but only that, plugin seems to be working fine, no errors whatsoever.
https://paste.gg/p/anonymous/882c4262468c4daaa72d41a03b26c241

### Expected behavior

To not spam my console

### Steps to reproduce

Join your 1.8 server with VelocityVanish and check the console

### LuckPerms webview link

https://luckperms.net/editor/pNIux9ZeGZ

### VelocityVanish's configuration file
```yml
# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
config_version: 7
default_language: en_US
show_dependency_suggestions: true
support_legacy_color_codes: false
force_vanish_if_first: true
bstats: true
sounds:
  command: ENTITY_EXPERIENCE_ORB_PICKUP
  vanish: ENTITY_EXPERIENCE_ORB_PICKUP
  unvanish: ENTITY_EXPERIENCE_ORB_PICKUP
vanish:
  actionbar: true
  remember: true
  see_as_spectator: true
  invincible: true
  fake_join_leave_message: true
  silent_open_container: true
  prevent:
    pickup: true
    block_break: false
    block_place: false
    interact: false
    advancement: true
hooks:
  essentials:
    force_prevent_private_messages: false
```

### Plugins

VelocityVanish
yes, I setup a fresh server to check

### Checklist

- [X] I am running the latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
- [ ] I ticked all of the boxes without actually reading them
