### ISSUE TITLE
when I come out of disappearance, no one sees me.

### ISSUE THREAD

**Issue by Kolya-YT** [Syrent/VelocityVanish#250]
### Server backend version

Paper 1.20.1

### Server backend Java version

Java 17

### Server Velocity version

Velocity 3.2.0-SNAPSHOT

### Server Velocity Java version

Java 17

### VelocityVanish version

v3.25.0-build.6-498a347

### Describe the bug

I go to the server, already in disappearance, but when I write /vanish to exit the disappearance, no one sees me, it only helps if I re-enter the server.

### Expected behavior

I must be seen

### Steps to reproduce

Just go to the server

### VelocityVanish's configuration file
```yml
# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
config_version: 7
default_language: en_US
show_dependency_suggestions: true

# IMPORTANT: Legacy code support is strongly discouraged. It adversely affects performance and lacks new Minecraft chat features.
support_legacy_color_codes: false

# If you're the first player to join the server, Vanish data may not synchronize correctly,
# and you may not enter vanish mode. With this option enabled, you can still enter vanish mode
# if you have operator privileges or the "velocityvanish.action.vanish.force" permission.
# If you weren't previously in vanish mode, you'll be unvanished after a few seconds.
force_vanish_if_first: true

bstats: true

# Leave sounds blank to disable them
# Example: command: ""
sounds:
  command: ENTITY_EXPERIENCE_ORB_PICKUP
  vanish: ENTITY_EXPERIENCE_ORB_PICKUP
  unvanish: ENTITY_EXPERIENCE_ORB_PICKUP

vanish:
  # Show players an actionbar when they are vanished
  actionbar: true
  
  # Remember vanish data after switching servers?
  # Note: Requires Velocity as a proxy server
  remember: true
  
  # Should we change player type to spectator in tablist for players who have permission to see vanished players?
  # Note: Requires ProtocolLib in versions lower than 1.19
  see_as_spectator: true
  
  # Should vanished players be protected from all damage sources?
  invincible: true
  
  # You can also achieve this by setting the fake join/leave message to blank in the language file
  fake_join_leave_message: true
  
  silent_open_container: true
  
  prevent:
    pickup: true
    block_break: false
    block_place: false
    interact: false
    # Only works on PaperMC servers (Paper, Purpur, Pufferfish, etc...)
    advancement: true

hooks:
  essentials:
    force_prevent_private_messages: false
```

### Plugins

Server Plugins (18):
[20:22:45 INFO]: Paper Plugins:
[20:22:45 INFO]:  - VelocityVanish
[20:22:45 INFO]: Bukkit Plugins:
[20:22:45 INFO]:  - AdvancedBan, Chatty, CoreProtect, CoreProtectTNT, DeluxeMenus, EasyArmorStands, *EasyWhitelist, GSit, InventoryRollbackPlus, InvisibleItemFrame
[20:22:45 INFO]:  InvSeePlusPlus, LuckPerms, PL-Hide, PlaceholderAPI, *PlayTime, sleep-most, TAB

### Checklist

- [x] I am running the latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
- [X] I ticked all of the boxes without actually reading them
